# Generated by Django 4.2.7 on 2023-11-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uyeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uyeno', models.IntegerField()),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('kullaniciAdi', models.CharField(max_length=25)),
                ('cinsiyet', models.CharField(max_length=5)),
            ],
        ),
    ]
