# Generated by Django 4.2.7 on 2023-11-27 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uyeler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icerikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar_soyad', models.CharField(max_length=50)),
                ('yazar_kullaniciAdi', models.CharField(max_length=50)),
                ('yazar_cinsiyet', models.CharField(max_length=5)),
                ('icerik_ismi', models.CharField(max_length=50)),
                ('yazar_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icerikler', to='uyeler.uyeler')),
            ],
        ),
    ]
