# Generated by Django 4.2.7 on 2023-12-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uyeler', '0003_uyeler_profilresmi_alter_icerikler_yazar_ad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uyeler',
            name='cv',
            field=models.CharField(default='', max_length=100),
        ),
    ]
